name: Auto PR

on:
  push:
    branches: [develop]

jobs:
  auto-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Reset develop branch
        run: |
          git fetch origin develop:develop
          git reset --hard develop
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: develop
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          title: 'chore: release next version'
          commit-message: 'chore: release next version'
