name: Release

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Install and build
        run: |
          npm i -g pnpm
          pnpm install
          pnpm build
      - name: Release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: pnpm run release
